"""add more users

Revision ID: 3a5a5ce0c959
Revises: dbc5df7443b9
Create Date: 2026-07-12 21:46:40.633059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a5a5ce0c959'
down_revision: Union[str, Sequence[str], None] = 'dbc5df7443b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nick_name')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('nick_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
