"""add more users

Revision ID: dbc5df7443b9
Revises: ca18336d8c80
Create Date: 2026-07-12 19:46:38.588832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbc5df7443b9'
down_revision: Union[str, Sequence[str], None] = 'ca18336d8c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('nick_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nick_name')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
